// <auto-generated />
using System;
using MagnetCoach.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MagnetCoach.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190326020828_TacticName")]
    partial class TacticName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MagnetCoach.Domain.Models.Ball", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsVisible");

                    b.Property<int>("Size");

                    b.HasKey("Id");

                    b.ToTable("Balls");
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumberColor");

                    b.Property<string>("ShirtColor");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberColor = "White",
                            ShirtColor = "Red"
                        },
                        new
                        {
                            Id = 2,
                            NumberColor = "White",
                            ShirtColor = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            NumberColor = "White",
                            ShirtColor = "Green"
                        },
                        new
                        {
                            Id = 4,
                            NumberColor = "Black",
                            ShirtColor = "Yellow"
                        },
                        new
                        {
                            Id = 5,
                            NumberColor = "White",
                            ShirtColor = "Purple"
                        },
                        new
                        {
                            Id = 6,
                            NumberColor = "Black",
                            ShirtColor = "Wihte"
                        },
                        new
                        {
                            Id = 7,
                            NumberColor = "White",
                            ShirtColor = "Black"
                        });
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("SportId");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.FormationLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FormationId");

                    b.Property<int>("NumberOfPlayers");

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("FormationLines");
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Frame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BallId");

                    b.Property<int?>("OpponentTeamId");

                    b.Property<int>("OwnTeamId");

                    b.Property<int>("TacticId");

                    b.HasKey("Id");

                    b.HasIndex("BallId");

                    b.HasIndex("OpponentTeamId");

                    b.HasIndex("OwnTeamId");

                    b.HasIndex("TacticId");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number");

                    b.Property<int>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasEmptyGoal");

                    b.Property<bool>("HasGoalkeeper");

                    b.Property<int>("MaxPlayers");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sports");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasEmptyGoal = false,
                            HasGoalkeeper = true,
                            MaxPlayers = 11,
                            Name = "Football",
                            Sports = 0
                        },
                        new
                        {
                            Id = 2,
                            HasEmptyGoal = true,
                            HasGoalkeeper = true,
                            MaxPlayers = 7,
                            Name = "Handball",
                            Sports = 1
                        },
                        new
                        {
                            Id = 3,
                            HasEmptyGoal = false,
                            HasGoalkeeper = false,
                            MaxPlayers = 5,
                            Name = "Basketball",
                            Sports = 3
                        },
                        new
                        {
                            Id = 4,
                            HasEmptyGoal = true,
                            HasGoalkeeper = true,
                            MaxPlayers = 6,
                            Name = "Ice Hockey",
                            Sports = 2
                        });
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Tactic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArenaPart");

                    b.Property<string>("Name");

                    b.Property<int>("PlayerSize");

                    b.Property<int>("SportId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.HasIndex("UserId");

                    b.ToTable("Tactics");
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EmptyGoal");

                    b.Property<int?>("GoalKeeperColorId");

                    b.Property<int>("PlayerColorId");

                    b.HasKey("Id");

                    b.HasIndex("GoalKeeperColorId");

                    b.HasIndex("PlayerColorId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testuser@test.com",
                            Name = "Test User",
                            PasswordHash = "hash123",
                            Salt = "salt123",
                            UserName = "TestUser1"
                        });
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Role");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Ball", b =>
                {
                    b.OwnsOne("MagnetCoach.Domain.Models.Position", "Position", b1 =>
                        {
                            b1.Property<int>("BallId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("PositionX");

                            b1.Property<int>("PositionY");

                            b1.HasKey("BallId");

                            b1.ToTable("Balls");

                            b1.HasOne("MagnetCoach.Domain.Models.Ball")
                                .WithOne("Position")
                                .HasForeignKey("MagnetCoach.Domain.Models.Position", "BallId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Formation", b =>
                {
                    b.HasOne("MagnetCoach.Domain.Models.Sport", "Sport")
                        .WithMany("Formations")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.FormationLine", b =>
                {
                    b.HasOne("MagnetCoach.Domain.Models.Formation", "Formation")
                        .WithMany("Lines")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Frame", b =>
                {
                    b.HasOne("MagnetCoach.Domain.Models.Ball", "Ball")
                        .WithMany()
                        .HasForeignKey("BallId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MagnetCoach.Domain.Models.Team", "OpponentTeam")
                        .WithMany()
                        .HasForeignKey("OpponentTeamId");

                    b.HasOne("MagnetCoach.Domain.Models.Team", "OwnTeam")
                        .WithMany()
                        .HasForeignKey("OwnTeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MagnetCoach.Domain.Models.Tactic", "Tactic")
                        .WithMany("Frames")
                        .HasForeignKey("TacticId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Player", b =>
                {
                    b.HasOne("MagnetCoach.Domain.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("MagnetCoach.Domain.Models.Position", "Position", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("PositionX");

                            b1.Property<int>("PositionY");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.HasOne("MagnetCoach.Domain.Models.Player")
                                .WithOne("Position")
                                .HasForeignKey("MagnetCoach.Domain.Models.Position", "PlayerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Tactic", b =>
                {
                    b.HasOne("MagnetCoach.Domain.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MagnetCoach.Domain.Models.User", "User")
                        .WithMany("Tactics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.Team", b =>
                {
                    b.HasOne("MagnetCoach.Domain.Models.Color", "GoalKeeperColor")
                        .WithMany()
                        .HasForeignKey("GoalKeeperColorId");

                    b.HasOne("MagnetCoach.Domain.Models.Color", "PlayerColor")
                        .WithMany()
                        .HasForeignKey("PlayerColorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MagnetCoach.Domain.Models.UserRole", b =>
                {
                    b.HasOne("MagnetCoach.Domain.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
